const Menu = [
  {"nombre":"Miga Cocido y Queso", "key": 1,"comida":"SandwichsMiga", "precio":{"entero":"$190","medio":"$100"},"ingredientes":["jamon cocido","queso","pan miga","mayonesa"]},
  {"nombre":"Miga Crudo y Queso", "key": 2, "comida":"SandwichsMiga", "precio":{"entero":"$250","medio":"$230"},"ingredientes":["jamon crudo","queso","pan miga","mayonesa"]},
  {"nombre":"Tostado", "key": 3, "comida":"SandwichsMiga", "precio":{"entero":"$200","medio":"$110"},"ingredientes":["jamon","queso","pan miga","mayonesa"]},
  {"nombre":"Carlito", "key": 4, "comida":"SandwichsMiga", "precio":{"entero":"$200","medio":"$110"},"ingredientes":["jamon","queso","pan miga","ketchup"]},
  {"nombre":"Triple", "key": 5, "comida":"SandwichsMiga", "precio":{"entero":"$300","medio":"$150"},"ingredientes":["jamon","queso","lechuga","tomate","pan miga","mayonesa"]},
  {"nombre":"Tostado Lomo", "key": 6, "comida":"SandwichsMiga", "precio":{"entero":"$560","medio":"$280"},"ingredientes":["jamon","queso","lomo","tomate","pan miga","mayonesa"]},
  {"nombre":"Carlito Especial", "key": 7, "comida":"SandwichsMiga", "precio":{"entero":"$320","medio":"$160"},"ingredientes":["jamon","queso","aceituna","morron","huevo","pan miga","ketchup"]},
  {"nombre":"Familiar Primavera", "key": 8, "comida":"SandwichsMiga", "precio":{"entero":"$440","medio":"$220"},"ingredientes":["jamon","queso","lechuga","tomate","pan familiar","mayonesa"]},
  {"nombre":"Gratinado Queso", "key": 1, "comida":"Gratinados", "precio":{"entero":"$260","medio":"$130"},"ingredientes":["jamon cocido","queso", "queso gratinado","pan miga","mayonesa"]},
  {"nombre":"Gratinado Napolitano", "key": 2, "comida":"Gratinados", "precio":{"entero":"$320","medio":"$160"},"ingredientes":["jamon cocido","queso", "queso gratinado","tomate","pan miga","mayonesa"]},
  {"nombre":"Gratinado Palmitos", "key": 3, "comida":"Gratinados", "precio":{"entero":"$340","medio":"$170"},"ingredientes":["jamon cocido","queso", "queso gratinado","palmitos","salsa golf","pan miga","mayonesa"]},
  {"nombre":"Gratinado Anana", "key": 4, "comida":"Gratinados", "precio":{"entero":"$380","medio":"$190"},"ingredientes":["jamon cocido","queso", "queso gratinado","ananá","pan miga","mayonesa"]},
  {"nombre":"Hamburguesa Especial", "key": 1, "comida":"SandwichsEspeciales", "precio":{"ConPapas":"$280","SinPapas":"$240"},"ingredientes":["jamon cocido","hamburguesa","queso", "tomate","lechuga","pan hamburguesa","mayonesa"]},
  {"nombre":"Familiar de Milanesa Especial", "key": 2, "comida":"SandwichsEspeciales", "precio":{"ConPapas":"$360","SinPapas":"$320"},"ingredientes":["jamon cocido","queso", "tomate","lechuga","milanesa","pan familiar","mayonesa"]},
  {"nombre":"Torpedo Milanesa Especial", "key": 3, "comida":"SandwichsEspeciales", "precio":{"ConPapas":"$390","SinPapas":"$350"},"ingredientes":["jamon cocido","queso", "tomate","lechuga","milanesa","pan familiar","mayonesa"]},
  {"nombre":"Familiar de Lomo Especial", "key": 4, "comida":"SandwichsEspeciales", "precio":{"ConPapas":"$390","SinPapas":"$350"},"ingredientes":["jamon cocido","queso", "tomate","lechuga","lomo","pan familiar","mayonesa"]},
  {"nombre":"Pizza de Muzzarella", "key": 1, "comida":"Pizzas", "precio":{"entero":"$340","medio":"$170"},"ingredientes":["muzzarella","aceitunas", "orégano"]},
  {"nombre":"Pizza de Muzzarella con Jamón", "key": 2, "comida":"Pizzas", "precio":{"entero":"$390","medio":"$190"},"ingredientes":["muzzarella","jamón","aceitunas", "orégano"]},
  {"nombre":"Pizza Napolitana", "key": 3, "comida":"Pizzas", "precio":{"entero":"$390","medio":"$190"},"ingredientes":["muzzarella","tomate","aceitunas", "orégano"]},
  {"nombre":"Pizza Especial", "key": 4, "comida":"Pizzas", "precio":{"entero":"$210","medio":"$420"},"ingredientes":["muzzarella","morron","jamón","huevo","aceitunas"]},
  {"nombre":"Pizza Palmitos", "key": 5, "comida":"Pizzas", "precio":{"entero":"$220","medio":"$440"},"ingredientes":["muzzarella","palmitos","salsa golf"]},
  {"nombre":"Pizza 4 quesos", "key": 6, "comida":"Pizzas", "precio":{"entero":"$220","medio":"$440"},"ingredientes":["muzzarella","queso roquefort","queso parmesano", "queso barra"]},
  {"nombre":"Pizza Cantinpalo", "key": 7, "comida":"Pizzas", "precio":{"entero":"$220","medio":"$440"},"ingredientes":["muzzarella","cantinpalo","aceitunas"]},
  {"nombre":"Pizza Roquefort", "key": 8, "comida":"Pizzas", "precio":{"entero":"$230","medio":"$460"},"ingredientes":["muzzarella","queso roquefort","aceitunas", "orégano"]},
  {"nombre":"Pizza Ananá", "key": 9, "comida":"Pizzas", "precio":{"entero":"$240","medio":"$480"},"ingredientes":["muzzarella","ananá","cerezas"]},
  {"nombre":"Papas Fritas", "key": 1, "comida":"Papas", "precio":{"grande":"$150","chica":"$120"},"ingredientes":["papas"]},
  {"nombre":"Papas Fritas con Salchichas", "key": 2, "comida":"Papas", "precio":{"grande":"$190","chica":"$160"},"ingredientes":["papa", "salchicha"]},
  {"nombre":"Papas Fritas con cheddar", "key": 3, "comida":"Papas", "precio":{"grande":"$200","chica":"$170"},"ingredientes":["papa", "queso cheddar"]},
  {"nombre":"Tortilla de papas", "key": 5, "comida":"Papas", "precio":{"grande":"$290","chica":"$180"},"ingredientes":["papa", "huevo",""]},
  {"nombre": "Ensalada Clásica", "key": 1, "comida":"Ensaladas", "precio": {"ing5": "$130", "ing3": "$100"}, "ingredientes": ["lechuga","tomate","huevo","zanahoria","cebolla"]},
  {"nombre": "Ensalada Especial", "key": 2, "comida":"Ensaladas", "precio": {"ing5": "$290", "ing3": "$220"}, "ingredientes": ["lechuga","tomate","huevo","zanahoria","cebolla","pollo","choclo","papas","palmito","jamón","queso"]},
  {"nombre": "Milanesa con papas o ensalada", "key":1, "comida":"MilanesaAlPlato", "precio": "$300", "ingredientes": ["milanesa de carne o pollo", "ensalada o papas"]},
  {"nombre": "Milanesa gratinada con papas o ensalada", "key":2, "comida":"MilanesaAlPlato", "precio": "$340", "ingredientes": ["milanesa de carne o pollo", "ensalada o papas", "queso"]},
  {"nombre": "Milanesa napolitana con papas o ensalada", "key":3, "comida":"MilanesaAlPlato", "precio": "$350", "ingredientes": ["milanesa de carne o pollo", "ensalada o papas", "queso", "tomate"]},
  {"nombre": "Milanesa 4 quesos con papas o ensalada", "key":4, "comida":"MilanesaAlPlato", "precio": "$350", "ingredientes": ["milanesa de carne o pollo", "ensalada o papas", "queso muzzarella", "queso roquefort","queso barra","queso parmesano"]},
  {"nombre": "Ñoquis con crema o tuco", "key": 1, "comida":"Pastas", "precio": "$220"},
  {"nombre": "Tallarines con crema o tuco", "key": 2, "comida":"Pastas", "precio": "$240"},
  {"nombre": "Ravioles carne y verdura con crema o tuco", "key": 3, "comida":"Pastas", "precio": "$250"},
  {"nombre": "Canelones carne y verdura con crema o tuco", "key": 4, "comida":"Pastas", "precio": "$260"},
  {"nombre": "Sorrentinos de jamón y queso con crema o tuco", "key": 5, "comida":"Pastas", "precio": "$280"},
  {"nombre": "Lomo Grillado a la plancha", "key": 1, "comida":"LomoAlPlato", "precio": "$360"},
  {"nombre": "Lomo Grillado a la crema o mostaza", "key": 2, "comida":"LomoAlPlato", "precio": "$410"},
  {"nombre": "Lomo Grillado al puerro o champiñon", "key": 3, "comida":"LomoAlPlato", "precio": "$430"},
  {"nombre": "Lomo Grillado al roquefort", "key": 4, "comida":"LomoAlPlato", "precio": "$450"},
  {"nombre": "Lomo Grillado a los cuatro quesos", "key": 5, "comida":"LomoAlPlato", "precio": "$460"},
  {"nombre": "Pollo Grillado", "key": 1, "comida":"PolloAlPlato",  "precio": "$300"},
  {"nombre": "Pollo Grillado a la crema o mostaza", "key": 2, "comida":"PolloAlPlato",  "precio": "$330"},
  {"nombre": "Pollo Grillado al puerro o champiñon", "key": 3, "comida":"PolloAlPlato",  "precio": "$360"},
  {"nombre": "Pollo Grillado al roquefort", "key": 4, "comida":"PolloAlPlato",  "precio": "$380"},
  {"nombre": "Pollo Grillado a los cuatro quesos", "key": 5, "comida":"PolloAlPlato",  "precio": "$380"},
  {"nombre": "Empanadas", "key": 1, "comida":"Empanadas",  "precio": {"unidad": "$60", "mediaDocena": "$330", "docena": "$650"},"ingredientes": ["carne salada o jamón y queso"]},
  {"nombre": "Tartas", "key": 2, "comida":"Tartas",  "precio": "Porción: $100","ingredientes": ["verdura o jamón y queso"]},
];

export default Menu;